### PR TITLE
Attempted fix m2m formset bug

### PR DESCRIPTION
**Pull request by hjwp**
this is an attempt at fixing https://github.com/wagtail/wagtail/issues/3412

includes unit tests.

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @hjwp, and sorry for the delay in reviewing!

Would you mind adding a test for the equivalent case with a `ClusterTaggableManager` inside a child formset, please? I know that's a setup that people are either keen to use or possibly using already (https://github.com/wagtail/wagtail/issues/1221), and at this point I'm not sure whether adding a `save_m2m` here will fix it, break it, or neither of the above :-) (If it's equally broken with or without this patch, then that's fine of course - we can chalk it up as out of scope for this PR.)

I'm wary that `ClusterForm` has some fiddly special-casing to decide whether to perform a pre-emptive `save_m2m`, so there's a chance that we might end up having to do the same thing here - but I _think_ that was dealing with vanilla `TaggableManager`s, and there's certainly no expectation for those to work here.

**Comment by hjwp** [comment]
Hi there, I'm having a look now, but I really don't understand `ClusterTaggableManager` so I have very little idea what I'm doing...

**Comment by hjwp** [comment]
in our newspaper -> 1-to-m -> articles -> m2m -> authors  relationship, which would go via a clustertaggablemanager?  would we replace "authors" with "tags" maybe?

**Comment by hjwp** [comment]
OK have had a  crack but it's causing some (?) spurious failures in a different test, no idea why.  can you take a look?

**Comment by gasman** [comment]
Looks like it's trying to add a `tagged_items` formset (and thus failing because there's no management form) - adding an explicit `formsets = []` to `ArticleForm.Meta` fixes it.

Which is all a bit unintuitive really - I'll do some more digging and see if it makes sense to change `formsets` to be empty unless explicitly specified. (That's probably a job for another PR though...)

**Comment by gasman** [comment]
Merged in c7f7c182631042076ea9dbd2fa5d84ba1cf4945f - thanks again @hjwp!

**Pull request closed without merging**
